'use strict'
module.exports = {
  POLITE_MASU: 'ます Polite',
  POLITE_DESU_VERB: 'です Polite',
  POLITE_MASEN: 'ません Polite Negative',
  POLITE_MASEN_DESHITA: 'ませんでした Polite Negative Past',
  POLITE_MASHITA: 'ました Polite past',
  POLITE_MASHOU: 'ましょう Polite Volitional',
  NEGATIVE_NAI_VERB: 'ない Negative',
  PLAIN_PAST: 'Plain Past',
  TE_FORM: 'て・で Form',
  POTENTIAL: 'Potential Form',
  POTENTIAL_PASSIVE: 'Potential Or Passive Form',
  PASSIVE: 'Passive Form',
  BA_FORM: 'ば Conditional Form',
  IMPERATIVE: 'Imperative Form',
  VOLITIONAL: 'Volitional Form',
  MASU_STEM: 'ます Stem',
  HEARSAY: 'そう Hearsay Form',
  CAUSATIVE: 'Causative Form',
  SHORTENED_CAUSATIVE: 'Shortened Causative Form',
  TARA: 'たら Conditional Form',
  NAKYA: 'なきゃ Casual "Must Do"',
  NAKUCHA: 'なくちゃ Casual "Must Do"',
  AGEKU: 'あげく・挙句 After Great Trouble',
  TAI: 'たい Want To Do',
  APPEARANCE: 'そう Appearance Form',
  NAIDE: 'ないで Without Doing',
  NA_COMMAND: 'な Negative Command (Do Not Do)',
  NEGATIVE_VOLITIONAL: 'まい Negative Volitional',
  NASAI: 'なさい Polite But Firm Command',
  ZU: 'ず Without Doing',
  ADVERB: 'く Adverbification',
  WA_PARTICLE: 'は Particle',
  IRU: 'ている・でいる Continuing State/Result',
  ARU: 'てある・である Form',
  ORU: 'ておる・でおる Form',
  KUDASAI: 'ください Polite Request',
  NU: 'ぬ Archaic Negative',
  FEMININE_WA_PARTICLE: 'わ Feminine Emphasis Particle',
  YO_PARTICLE: 'よ Emphasis Particle',
  NE_PARTICLE: 'ね Agreement Seeking Particle',
  NA_PARTICLE: 'な Masculine Emphasis Particle',
  ZO_PARTICLE: 'ぞ Rough/Casual Emphasis Particle',
  ZE_PARTICLE: 'ぜ Rough/Casual Emphasis Particle',
  KA_PARTICLE: 'か Question Particle',
  GA_PARTICLE: 'が But',
  SA_PARTICLE: 'さ Emphasis/Filler Particle',
  MADE_PARTICLE: 'まで Until',
  KARA_PARTICLE: 'から Since, From',
  KEDO_PARTICLE: 'けど・けれど・けれども But',
  NONI_PARTICLE: 'のに Even Though, Despite',
  POLITE_DESHOU: 'でしょう Polite "Probably"',
  DAROU: 'だろう Probably',
  POLITE_ITADAKU: 'いただく Polite/Humble Receive Favor',
  MORAU: 'もらう Casual Receive Favor',
  BEKI: 'べき Must Do',
  OKU: 'ておく・でおく To Do Something In Preparation',
  KURERU: 'くれる To Give (Toward Speaker)',
  AGERU: 'あげる To Give (Away From Speaker)',
  WA_AFTER_TE: 'は Particle',
  MO_AFTER_TE: 'も Particle (Even, Even If)',
  II: 'いい Good, Okay',
  DA: 'だ Copula',
  OCCASIONAL_OCCURANCE_ARU: 'ことがある Occasional Occurance ・ It Happens Sometimes',
  EXPLANATORY_NO_PARTICLE: 'の Explanatory Particle',
  KOTO_NOMINALIZER: 'こと Nominalizer',
  KOTO_NI_SURU: 'ことにする Decide To Do ・ Settle On Doing',
  KOTO_NI_NARU: 'ことになる Has Been Decided ・ Has Become The Case',
  MAE: '前・まえ Before Doing',
  GA_HAYAI_KA: 'が早いか As Soon As',
  MITAI: 'みたい Looks Like ・ Seems Like',
  RASHII: 'らしい Looks Like ・ Seems Like',
  GARU: 'がる Appearing To Want',
  MASU_STEM_WA_SHINAI: 'ます Stem しない Strong Emphasis On Not Doing',
  NAGARA: 'ながら While',
  GACHI: 'がち Prone To ・ Unfortunate Tendency',
  KATA: '方・かた Way Of Doing',
  NIKUI: 'にくい Difficult To Do',
  YASUI: 'やすい Easy To Do',
  SUGI: '過ぎ・すぎ Overdoing',
  SUGIRU: '過ぎる・すぎる Overdoing',
  MASU_STEM_NI: 'ます Stem に Going To Do',
  NAKUTE_NAKEREBA_IKENAI_NARANAI: 'なくて・なければ + いけない・ならない Must Do',
  TE_IKENAI_NARANAI: 'ていけない・てならない Must Not Do',
  TE_DAME: 'だめ・駄目 Bad ・ Should Not',
  NAKUTE_NAKEREBA_DAME: 'なくて・なければ + だめ・駄目 Must Do',
  SHIMAU: 'しまう To Do Unfortunately ・ To Do Completely',
  CHAU: 'ちゃう Casual Contraction Of てしまう',
  MIRU: 'みる To Try To Do',
  HOSHII: 'ほしい・欲しい To Want Someone To Do Something',
  TE_KARA: 'から Since, After',
  TE_KURU: 'てくる・でくる Gradual Change (Toward Speaker)',
  TE_IKU: 'ていく・でいく Gradual Change (Away From Speaker)',
  KAMAU: 'かまう To Mind ・ To Care',
  SUMANAI: 'すまない Sorry!',
  SUMIMASEN: 'すみません Polite Sorry',
  JIMAU: 'じまう Casual Contraction Of でしまう',
  CHIMAU: 'ちまう Casual Contraction Of てしまう',
  JAU: 'じゃう Casual Contraction Of でしまう',
  TARI: 'たり Et Cetera',
  TA_BAKARI: 'たばかり・だばかり To Have Just Done',
  HOU_GA_II: 'ほうがいい Better ・ Preferable',
  YOU: 'よう Appearance ・ It Seems That Way',
  HAZU: 'はず Expectation',
  NARU: 'なる To Become',
  DE_ARU: 'である Formal ・ Literary Copula',
  TSUTSU_ARU: 'つつある In The Process Of',
  GATAI: 'がたい Difficult To Do (Due To Emotional Reasons)',
  SHIDAI: '次第・しだい Immediately After',
  YAGARU: 'やがる Shows Contempt For The Action Being Done',
  BEKU: 'べく In Order To',
  GODAN_VERB: 'godan verb',
  ICHIDAN_VERB: 'ichidan verb',
  ADJECTIVE: 'adjective',
  SENTENCE_ENDING_PARTICLES: 'sentence ending particles (silent)',
  NEGATIVE_ARU_OR_IRU: 'Negative ある or いる',
  SHORT_IRU: 'てる・でる Continuing State/Result',
};